// AUTO-GENERATED by generate-home-manifest.py — do not edit by hand.
window.HUB_MODULES = [
 {
  "key": "listening",
  "title": "Listening 听力",
  "desc": "剑桥 14–21 真题音频，逐段精听、倍速、A-B 复读。",
  "href": "Listening-audios/index.html",
  "icon": "🎧",
  "accent": "#7b8cff",
  "ready": true
 },
 {
  "key": "writing",
  "title": "Writing 写作",
  "desc": "70 篇真题双语范文，小作文 / 大作文一键切换。",
  "href": "Writing-examples/index.html",
  "icon": "✍️",
  "accent": "#9b6cff",
  "ready": true
 },
 {
  "key": "speaking",
  "title": "Speaking 口语",
  "desc": "口语范文与答题思路（即将上线）。",
  "href": "Speaking-answers/index.html",
  "icon": "🗣️",
  "accent": "#5b6cff",
  "ready": false
 },
 {
  "key": "tutorials",
  "title": "Tutorials 教程",
  "desc": "写作带练教程：主线题走通、按题型/话题摊开、附录语料库。",
  "href": "Tutorials/index.html",
  "icon": "📚",
  "accent": "#b07ed6",
  "ready": true
 }
];
