import os, json, re

HERE = os.path.dirname(os.path.abspath(__file__))   # .../UI/tools
UI = os.path.dirname(HERE)                            # .../UI
REPO = os.path.dirname(UI)                            # repo root

# Page index.html now lives INSIDE Listening-audios/, so file paths in the
# manifest must be relative to that folder (not to the repo root).
root = os.path.join(REPO, "Listening-audios")
root_abs = os.path.join(REPO, "Listening-audios")

books = []
for book in sorted(os.listdir(root)):
    bpath = os.path.join(root, book)
    if not os.path.isdir(bpath):
        continue
    m = re.search(r'(\d+)', book)
    book_num = int(m.group(1)) if m else 0
    tests = []
    for test in sorted(os.listdir(bpath)):
        tpath = os.path.join(bpath, test)
        if not os.path.isdir(tpath):
            continue
        tm = re.search(r'(\d+)', test)
        test_num = int(tm.group(1)) if tm else 0
        sections = []
        for f in sorted(os.listdir(tpath)):
            if not f.lower().endswith('.mp3'):
                continue
            fpath = os.path.join(tpath, f)
            rel = os.path.relpath(fpath, root_abs).replace("\\", "/")
            sm = re.search(r'Section\s*(\d+)', f)
            sec_num = int(sm.group(1)) if sm else 0
            sections.append({
                "title": f.replace('.mp3', ''),
                "section": sec_num,
                "file": rel,
            })
        if sections:
            tests.append({"title": test, "test": test_num, "sections": sections})
    if tests:
        books.append({"title": book, "book": book_num, "tests": tests})

out = "// AUTO-GENERATED by generate-listening-manifest.py - do not edit by hand.\n"
out += "window.AUDIO_LIBRARY = " + json.dumps(books, ensure_ascii=False, indent=2) + ";\n"
with open(os.path.join(UI, "listening", "manifest.js"), "w", encoding="utf-8") as fh:
    fh.write(out)

total = sum(len(t["sections"]) for b in books for t in b["tests"])
print(f"books={len(books)} tests={sum(len(b['tests']) for b in books)} tracks={total}")
