#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Scan Writing-examples/Writing-*.md and produce UI/writing-manifest.js
(window.WRITING_LIBRARY).

Pure standard library — no pip install needed. Each entry only records
METADATA + the file path; the actual Markdown body is NOT inlined.
The browser fetches the .md on demand (writing-reader.loadEssay) and
renders it with the dependency-free engine in writing-reader.js.

Because the page fetches files at runtime, it must be served over http
(file:// blocks fetch). Re-run this script only when you add/remove/
rename an essay .md file.

    python UI/generate-writing-manifest.py
"""
import os
import re
import json

HERE = os.path.dirname(os.path.abspath(__file__))   # .../UI/tools
UI = os.path.dirname(HERE)                            # .../UI
REPO = os.path.dirname(UI)                            # repo root
WEX = os.path.join(REPO, "Writing-examples")


def main():
    if not os.path.isdir(WEX):
        raise SystemExit("ERROR: %s not found" % WEX)

    entries = []
    for fn in sorted(os.listdir(WEX)):
        if not (fn.startswith("Writing-") and fn.endswith(".md")):
            continue
        date = fn[len("Writing-"):-len(".md")]        # YYYY-MM-DD

        # Read only enough to derive the list title (the first H1).
        # The full body is NOT loaded here — the browser fetches the
        # .md file at runtime via writing-reader.loadEssay().
        path = os.path.join(WEX, fn)
        with open(path, encoding="utf-8") as fh:
            head = fh.read(4096)
        m = re.search(r"^#\s+(.+)$", head, flags=re.M)
        title = m.group(1).strip() if m else date

        entries.append({"date": date, "title": title, "file": fn})

    # study order: oldest -> newest
    entries.sort(key=lambda e: e["date"])

    out = "// AUTO-GENERATED by generate-writing-manifest.py — do not edit by hand.\n"
    out += "window.WRITING_LIBRARY = " + json.dumps(entries, ensure_ascii=False, indent=1) + ";\n"

    dest = os.path.join(UI, "writing", "manifest.js")
    with open(dest, "w", encoding="utf-8") as fh:
        fh.write(out)

    print("wrote %d essays -> %s" % (len(entries), dest))


if __name__ == "__main__":
    main()
