#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Scan subsite folders and (re)build UI/home/manifest.js (window.HUB_MODULES).

Pure standard library. Edit the MODULES list below to add/remove/reorder
subsite entry cards on the root hub page, then re-run:

    python UI/tools/generate-home-manifest.py
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))   # .../UI/tools
UI = os.path.dirname(HERE)                            # .../UI
REPO = os.path.dirname(UI)                            # repo root

MODULES = [
    {
        "key": "listening",
        "title": "Listening 听力",
        "desc": "剑桥 14–21 真题音频，逐段精听、倍速、A-B 复读。",
        "href": "Listening-audios/index.html",
        "icon": "🎧",
        "accent": "#7b8cff",
        "ready": True,
    },
    {
        "key": "writing",
        "title": "Writing 写作",
        "desc": "70 篇真题双语范文，小作文 / 大作文一键切换。",
        "href": "Writing-examples/index.html",
        "icon": "✍️",
        "accent": "#9b6cff",
        "ready": True,
    },
    {
        "key": "speaking",
        "title": "Speaking 口语",
        "desc": "口语范文与答题思路（即将上线）。",
        "href": "Speaking-answers/index.html",
        "icon": "🗣️",
        "accent": "#5b6cff",
        "ready": False,
    },
    {
        "key": "tutorials",
        "title": "Tutorials 教程",
        "desc": "写作带练教程与附录语料库（即将上线）。",
        "href": "Tutorials/index.html",
        "icon": "📚",
        "accent": "#b07ed6",
        "ready": False,
    },
]


def main():
    out = "// AUTO-GENERATED by generate-home-manifest.py — do not edit by hand.\n"
    out += "window.HUB_MODULES = " + __import__("json").dumps(
        MODULES, ensure_ascii=False, indent=1
    ) + ";\n"
    dest = os.path.join(UI, "home", "manifest.js")
    with open(dest, "w", encoding="utf-8") as fh:
        fh.write(out)
    print("wrote %d modules -> %s" % (len(MODULES), dest))


if __name__ == "__main__":
    main()
